const QUESTIONS_PART2 = [
    { id:"e001", subject:"经济", subjectCode:"0455", topic:"供需 Supply & Demand", difficulty:"easy", type:"single",
      question:"需求定律是？Law of demand states?",
      options:["价格上升，需求量增加","价格上升，需求量减少","价格与需求无关","收入增加，需求减少"], answer:1,
      explanation:"需求定律 Law of Demand：价格上升，需求量下降（反向关系）。需求曲线向下倾斜 Downward sloping。",
      keywords:["需求定律 Law of demand","价格 Price","需求量 Quantity demanded","需求曲线 Demand curve"], isHot:true },
    { id:"e002", subject:"经济", subjectCode:"0455", topic:"弹性 Elasticity", difficulty:"medium", type:"single",
      question:"必需品的需求价格弹性通常是？PED for necessities is usually?",
      options:["富有弹性","缺乏弹性","单位弹性","完全弹性"], answer:1,
      explanation:"必需品 Necessity 需求量对价格变化不敏感，PED < 1（缺乏弹性 Inelastic）。奢侈品 Luxury 富有弹性 Elastic。",
      keywords:["需求价格弹性 PED","必需品 Necessity","奢侈品 Luxury","富有弹性 Elastic","缺乏弹性 Inelastic"], isHot:true },
    { id:"e003", subject:"经济", subjectCode:"0455", topic:"市场结构 Market", difficulty:"medium", type:"single",
      question:"完全竞争市场的特点是？Feature of perfect competition?",
      options:["只有一个卖家","产品有差异","许多卖家，同质产品","高进入壁垒"], answer:2,
      explanation:"完全竞争 Perfect competition：许多买卖双方、同质产品 Homogeneous、自由进出、完全信息、企业是价格接受者 Price taker。",
      keywords:["完全竞争 Perfect competition","同质产品 Homogeneous","价格接受者 Price taker","市场结构 Market structure"], isHot:true },
    { id:"e004", subject:"经济", subjectCode:"0455", topic:"宏观 Macro", difficulty:"easy", type:"single",
      question:"GDP 是指？GDP stands for?",
      options:["国内生产总值","国民生产总值","人均收入","消费价格指数"], answer:0,
      explanation:"GDP = Gross Domestic Product 国内生产总值，一国境内一定时期生产的最终产品和服务的总价值。",
      keywords:["国内生产总值 GDP","经济增长 Economic growth","国民收入 National income"], isHot:true },
    { id:"e005", subject:"经济", subjectCode:"0455", topic:"通胀 Inflation", difficulty:"medium", type:"single",
      question:"需求拉动型通胀的原因是？Demand-pull inflation caused by?",
      options:["生产成本上升","总需求超过总供给","货币供应减少","失业率上升"], answer:1,
      explanation:"需求拉动型通胀 Demand-pull：总需求 AD 超过总供给 AS，物价普遍上涨。'太多货币追逐太少商品'。",
      keywords:["通货膨胀 Inflation","需求拉动 Demand-pull","总需求 Aggregate demand","物价 Price level"], isHot:true },
    { id:"e006", subject:"经济", subjectCode:"0455", topic:"供需 Supply & Demand", difficulty:"medium", type:"single",
      question:"供给曲线向上倾斜是因为？Supply curve slopes upward because?",
      options:["价格越高利润越高，企业愿意多生产","消费者喜欢高价","生产成本随产量下降","政府规定"], answer:0,
      explanation:"价格越高，生产者利润越高，愿意增加供给量。供给定律 Law of Supply：价格与供给量正向关系。",
      keywords:["供给定律 Law of supply","供给曲线 Supply curve","利润 Profit","生产者 Producer"], isHot:false },
    { id:"e007", subject:"经济", subjectCode:"0455", topic:"宏观 Macro", difficulty:"hard", type:"single",
      question:"扩张性财政政策包括？Expansionary fiscal policy includes?",
      options:["增税+减支","减税+增支","加息","减少货币供应"], answer:1,
      explanation:"扩张性财政政策 Expansionary fiscal policy：减税 Tax cut + 增加政府支出 Government spending，刺激总需求，应对衰退。",
      keywords:["财政政策 Fiscal policy","扩张性 Expansionary","政府支出 Government spending","税收 Tax"], isHot:true },
    { id:"e008", subject:"经济", subjectCode:"0455", topic:"市场失灵 Market failure", difficulty:"medium", type:"single",
      question:"负外部性的例子是？Example of negative externality?",
      options:["接种疫苗","工厂污染","教育","研发"], answer:1,
      explanation:"负外部性 Negative externality：生产/消费对第三方造成成本，如污染 Pollution。正外部性如疫苗、教育。",
      keywords:["外部性 Externality","市场失灵 Market failure","污染 Pollution","第三方 Third party"], isHot:true },
    { id:"e009", subject:"经济", subjectCode:"0455", topic:"弹性 Elasticity", difficulty:"hard", type:"single",
      question:"如果 PED = 0.5，价格上升 10%，需求量变化？PED=0.5, price +10%, quantity changes by?",
      options:["减少 5%","增加 5%","减少 20%","减少 10%"], answer:0,
      explanation:"PED = %ΔQ / %ΔP，0.5 = %ΔQ / 10%，%ΔQ = 5%。价格上升需求量减少，所以减少 5%。",
      keywords:["需求价格弹性 PED","需求量 Quantity demanded","百分比变化 Percentage change"], isHot:true },
    { id:"e010", subject:"经济", subjectCode:"0455", topic:"宏观 Macro", difficulty:"medium", type:"single",
      question:"失业率是指？Unemployment rate is?",
      options:["失业人口占总人口比例","失业人口占劳动力比例","没有工作的人数","退休人口比例"], answer:1,
      explanation:"失业率 Unemployment rate = 失业人数 / 劳动力 Labour force × 100%。劳动力=就业+失业（有工作能力且愿意工作）。",
      keywords:["失业 Unemployment","劳动力 Labour force","就业率 Employment","劳动参与率 Participation rate"], isHot:true },
    { id:"e011", subject:"经济", subjectCode:"0455", topic:"市场结构 Market", difficulty:"hard", type:"single",
      question:"垄断市场的特点是？Monopoly feature?",
      options:["许多卖家","唯一卖家，高壁垒","同质产品","价格接受者"], answer:1,
      explanation:"垄断 Monopoly：唯一卖家 Single seller、高进入壁垒 High barriers、产品无替代品、价格制定者 Price maker。",
      keywords:["垄断 Monopoly","进入壁垒 Barriers to entry","价格制定者 Price maker","市场势力 Market power"], isHot:true },
    { id:"e012", subject:"经济", subjectCode:"0455", topic:"宏观 Macro", difficulty:"medium", type:"single",
      question:"货币政策的工具包括？Monetary policy tools include?",
      options:["政府支出","利率和货币供应","税收","补贴"], answer:1,
      explanation:"货币政策 Monetary policy：央行通过利率 Interest rate、货币供应 Money supply、准备金率等调节经济。财政政策是税收和支出。",
      keywords:["货币政策 Monetary policy","利率 Interest rate","央行 Central bank","货币供应 Money supply"], isHot:true },
    { id:"e013", subject:"经济", subjectCode:"0455", topic:"供需 Supply & Demand", difficulty:"easy", type:"single",
      question:"市场均衡是指？Market equilibrium means?",
      options:["供给量大于需求量","需求量大于供给量","供给量等于需求量","价格为零"], answer:2,
      explanation:"均衡 Equilibrium：在特定价格下，供给量 Quantity supplied 等于需求量 Quantity demanded，供需曲线在均衡价格处相交。",
      keywords:["均衡 Equilibrium","均衡价格 Equilibrium price","供给 Supply","需求 Demand"], isHot:true },
    { id:"e014", subject:"经济", subjectCode:"0455", topic:"宏观 Macro", difficulty:"hard", type:"single",
      question:"经济周期的四个阶段是？Four phases of business cycle?",
      options:["繁荣、衰退、萧条、复苏","增长、下降、平稳、波动","通胀、通缩、滞胀、复苏","扩张、顶峰、收缩、谷底"], answer:3,
      explanation:"经济周期 Business cycle：扩张 Expansion → 顶峰 Peak → 收缩 Contraction → 谷底 Trough，循环往复。GDP 波动。",
      keywords:["经济周期 Business cycle","扩张 Expansion","衰退 Recession","GDP"], isHot:false },
    { id:"e015", subject:"经济", subjectCode:"0455", topic:"市场失灵 Market failure", difficulty:"medium", type:"single",
      question:"公共物品的特征是？Public goods feature?",
      options:["竞争性和排他性","非竞争性和非排他性","只有政府能消费","价格很高"], answer:1,
      explanation:"公共物品 Public goods：非竞争性 Non-rival（一人消费不减少他人）+ 非排他性 Non-excludable（无法阻止他人使用）。如国防、路灯。",
      keywords:["公共物品 Public goods","非竞争性 Non-rival","非排他性 Non-excludable","搭便车 Free rider"], isHot:true },
    { id:"esl001", subject:"英语", subjectCode:"0510", topic:"语法-时态 Tenses", difficulty:"easy", type:"single",
      question:"Choose: She ___ to school every day.",
      options:["go","goes","going","went"], answer:1,
      explanation:"every day 表示习惯性动作，用一般现在时 Simple present。主语 she 是第三人称单数，动词加 -es：goes。",
      keywords:["一般现在时 Simple present","第三人称单数 Third person singular","习惯 Habit"], isHot:true },
    { id:"esl002", subject:"英语", subjectCode:"0510", topic:"语法-时态 Tenses", difficulty:"medium", type:"single",
      question:"Choose: I ___ my homework when the phone rang.",
      options:["did","was doing","have done","am doing"], answer:1,
      explanation:"过去进行时 Past continuous：过去某个时刻正在进行的动作。结构 was/were + V-ing。电话响时我正在做作业。",
      keywords:["过去进行时 Past continuous","同时发生 Simultaneous","动词-ing形式 Participle"], isHot:true },
    { id:"esl003", subject:"英语", subjectCode:"0510", topic:"语法-时态 Tenses", difficulty:"medium", type:"single",
      question:"Choose: ___ you ever ___ to Japan?",
      options:["Did, been","Have, been","Are, being","Do, be"], answer:1,
      explanation:"ever 常与现在完成时 Present perfect 连用，表示'曾经'。结构 have/has + 过去分词。Have you ever been to Japan?",
      keywords:["现在完成时 Present perfect","曾经 Ever","过去分词 Past participle","经历 Experience"], isHot:true },
    { id:"esl004", subject:"英语", subjectCode:"0510", topic:"语法-被动语态 Passive", difficulty:"medium", type:"single",
      question:"Choose: The letter ___ yesterday.",
      options:["was sent","is sent","sent","sends"], answer:0,
      explanation:"yesterday 表过去，用一般过去时被动 Past passive：was/were + 过去分词。letter 单数 → was sent。",
      keywords:["被动语态 Passive voice","一般过去时 Past simple","过去分词 Past participle"], isHot:true },
    { id:"esl005", subject:"英语", subjectCode:"0510", topic:"语法-条件句 Conditional", difficulty:"hard", type:"single",
      question:"Choose: If it rains tomorrow, we ___ at home.",
      options:["stay","will stay","would stay","stayed"], answer:1,
      explanation:"第一条件句 First conditional：真实可能的将来。结构 If + 一般现在时, will + 动词原形。",
      keywords:["第一条件句 First conditional","将来 Future","真实条件 Real condition"], isHot:true },
    { id:"esl006", subject:"英语", subjectCode:"0510", topic:"语法-条件句 Conditional", difficulty:"hard", type:"single",
      question:"Choose: If I ___ richer, I would travel the world.",
      options:["am","was","were","would be"], answer:2,
      explanation:"第二条件句 Second conditional：与现在事实相反。If + 过去式, would + V。be 动词在虚拟语气中用 were（所有人称）。",
      keywords:["第二条件句 Second conditional","虚拟语气 Subjunctive","假设 Hypothesis","与事实相反 Unreal"], isHot:true },
    { id:"esl007", subject:"英语", subjectCode:"0510", topic:"语法-条件句 Conditional", difficulty:"hard", type:"single",
      question:"Choose: If I ___ harder, I would have passed the exam.",
      options:["study","studied","had studied","would study"], answer:2,
      explanation:"第三条件句 Third conditional：与过去事实相反。结构 If + 过去完成时 Past perfect, would have + 过去分词。",
      keywords:["第三条件句 Third conditional","过去完成时 Past perfect","遗憾 Regret","与过去相反"], isHot:true },
    { id:"esl008", subject:"英语", subjectCode:"0510", topic:"词汇-易混词 Confusing words", difficulty:"medium", type:"single",
      question:"Choose: I have ___ friends here. (meaning: some but not many)",
      options:["few","a few","little","a little"], answer:1,
      explanation:"a few = 有一些（肯定含义），修饰可数名词。few = 几乎没有（否定含义）。little/a little 修饰不可数名词。",
      keywords:["few / a few","可数名词 Countable","量词 Quantifier","肯定/否定 Positive/Negative"], isHot:true },
    { id:"esl009", subject:"英语", subjectCode:"0510", topic:"词汇-易混词 Confusing words", difficulty:"medium", type:"single",
      question:"Choose: The book is very ___ . I can't put it down.",
      options:["boring","interested","interesting","bored"], answer:2,
      explanation:"interesting 修饰事物（令人感兴趣的），interested 修饰人（感到有兴趣的）。boring/boring 同理。",
      keywords:["-ing / -ed 形容词","修饰事物 vs 人","情感形容词 Emotion adjective"], isHot:true },
    { id:"esl010", subject:"英语", subjectCode:"0510", topic:"语法-冠词 Article", difficulty:"easy", type:"single",
      question:"Choose: ___ apple a day keeps the doctor away.",
      options:["A","An","The","-"], answer:1,
      explanation:"apple 以元音音素 /æ/ 开头，用 an。a 用于辅音音素前。注意看发音不看字母：an hour, a university。",
      keywords:["不定冠词 Indefinite article","元音音素 Vowel sound","辅音音素 Consonant sound"], isHot:true },
    { id:"esl011", subject:"英语", subjectCode:"0510", topic:"语法-介词 Preposition", difficulty:"medium", type:"single",
      question:"Choose: She is good ___ mathematics.",
      options:["in","at","on","for"], answer:1,
      explanation:"be good at = 擅长于。固定搭配。be good for = 对...有益。be good to = 对...好。介词是 ESL 高频考点。",
      keywords:["介词 Preposition","固定搭配 Collocation","be good at","短语动词 Phrasal verb"], isHot:true },
    { id:"esl012", subject:"英语", subjectCode:"0510", topic:"语法-从句 Clause", difficulty:"hard", type:"single",
      question:"Choose: This is the girl ___ won the competition.",
      options:["which","who","whom","whose"], answer:1,
      explanation:"先行词是人（girl），在从句中作主语，用 who。which 指物，whom 作宾语，whose 表所属。定语从句 Relative clause。",
      keywords:["定语从句 Relative clause","关系代词 Relative pronoun","先行词 Antecedent","主语 Subject"], isHot:true },
    { id:"esl013", subject:"英语", subjectCode:"0510", topic:"写作-连接词 Linking", difficulty:"medium", type:"single",
      question:"Choose: He was tired; ___, he continued working.",
      options:["therefore","however","moreover","otherwise"], answer:1,
      explanation:"前后转折：累了但仍继续工作。however 表转折'然而'。therefore 因果，moreover 递进，otherwise 否则。",
      keywords:["连接词 Linking word","转折 Contrast","递进 Addition","因果 Cause/effect","写作 Writing"], isHot:true },
    { id:"esl014", subject:"英语", subjectCode:"0510", topic:"阅读理解 Reading", difficulty:"medium", type:"single",
      question:"Read: 'Despite the rain, we went out.' What does this mean?",
      options:["We stayed home because of rain","We went out even though it was raining","The rain stopped","We went out after the rain"], answer:1,
      explanation:"despite = 尽管（后接名词/动名词），表让步 Concession。= in spite of。although 后接从句。",
      keywords:["despite / in spite of","让步 Concession","尽管 Although","阅读理解 Reading comprehension"], isHot:true },
    { id:"esl015", subject:"英语", subjectCode:"0510", topic:"语法-情态动词 Modal", difficulty:"medium", type:"single",
      question:"Choose: You ___ smoke here. It's forbidden.",
      options:["mustn't","needn't","don't have to","mightn't"], answer:0,
      explanation:"mustn't = 禁止（不允许）。needn't/don't have to = 不必。mightn't = 可能不。禁止是 mustn't 不是 don't have to。",
      keywords:["情态动词 Modal verb","禁止 Prohibition","mustn't vs needn't","义务 Obligation"], isHot:true },
    { id:"esl016", subject:"英语", subjectCode:"0510", topic:"语法-非谓语 Infinitive", difficulty:"hard", type:"single",
      question:"Choose: I enjoy ___ books.",
      options:["read","to read","reading","reads"], answer:2,
      explanation:"enjoy 后接动名词 Gerund（V-ing）。类似动词：mind, finish, suggest, avoid, practice。want/hope/decide 后接不定式 to do。",
      keywords:["动名词 Gerund","不定式 Infinitive","动词搭配 Verb pattern","非谓语 Non-finite"], isHot:true },
    { id:"esl017", subject:"英语", subjectCode:"0510", topic:"词汇-短语动词 Phrasal verb", difficulty:"medium", type:"single",
      question:"Choose: The meeting was ___ until next week.",
      options:["put off","put up","put out","put on"], answer:0,
      explanation:"put off = 推迟 Postpone。put up = 张贴/举起，put out = 熄灭，put on = 穿上。短语动词 Phrasal verb 是 ESL 必考点。",
      keywords:["短语动词 Phrasal verb","推迟 Postpone","put off","动词短语 Verb phrase"], isHot:true },
    { id:"esl018", subject:"英语", subjectCode:"0510", topic:"语法-比较级 Comparative", difficulty:"easy", type:"single",
      question:"Choose: She is ___ than her sister.",
      options:["tall","taller","tallest","more tall"], answer:1,
      explanation:"than 是比较级标志。单音节词加 -er：taller。多音节词用 more：more beautiful。最高级用 the + -est/most。",
      keywords:["比较级 Comparative","最高级 Superlative","than","比较 Comparison"], isHot:true },
    { id:"esl019", subject:"英语", subjectCode:"0510", topic:"写作-正式用语 Formal", difficulty:"hard", type:"single",
      question:"Which is the most formal way to start a complaint letter?",
      options:["Hey, I'm writing to complain...","I am writing to express my dissatisfaction regarding...","Yo, this product is terrible!","What's up with this product?"], answer:1,
      explanation:"正式信函 Formal letter 用完整句式和礼貌用语。'I am writing to express my dissatisfaction regarding...' 是标准投诉信开头。",
      keywords:["正式写作 Formal writing","投诉信 Complaint letter","语气 Tone","礼貌用语 Polite expression"], isHot:true },
    { id:"esl020", subject:"英语", subjectCode:"0510", topic:"听力/口语 Listening", difficulty:"medium", type:"single",
      question:"In listening, 'I couldn't agree more' means:",
      options:["I disagree completely","I strongly agree","I am not sure","I don't care"], answer:1,
      explanation:"'I couldn't agree more' = 我完全同意（字面：我不能同意更多了=已经同意到极限）。这是常见的口语强调同意表达。",
      keywords:["口语表达 Idiomatic expression","同意 Agreement","强调 Emphasis","听力 Listening"], isHot:false },
    { id:"esl021", subject:"英语", subjectCode:"0510", topic:"语法-时态 Tenses", difficulty:"hard", type:"single",
      question:"Choose: By next year, I ___ English for 10 years.",
      options:["will study","will have studied","study","have studied"], answer:1,
      explanation:"将来完成时 Future perfect：by + 将来时间点，表示到那时将已完成。结构 will have + 过去分词。",
      keywords:["将来完成时 Future perfect","by + 时间","完成 Completion","将来 Future"], isHot:true },
    { id:"esl022", subject:"英语", subjectCode:"0510", topic:"词汇-同义词 Synonym", difficulty:"medium", type:"single",
      question:"Which word is closest in meaning to 'abundant'?",
      options:["scarce","plentiful","expensive","dangerous"], answer:1,
      explanation:"abundant = 丰富的、大量的 = plentiful。scarce 是反义词（稀缺的）。同义词 Synonym 是阅读高频考点。",
      keywords:["同义词 Synonym","反义词 Antonym","词汇 Vocabulary","abundant 丰富的"], isHot:false },
    { id:"ict001", subject:"ICT", subjectCode:"0417", topic:"硬件 Hardware", difficulty:"easy", type:"single",
      question:"Which is an input device? 哪个是输入设备？",
      options:["Monitor 显示器","Printer 打印机","Keyboard 键盘","Speaker 音箱"], answer:2,
      explanation:"键盘 Keyboard 是输入设备 Input device。显示器、打印机、音箱是输出设备 Output device。触摸屏 Touchscreen 既是输入也是输出。",
      keywords:["输入设备 Input device","输出设备 Output device","键盘 Keyboard","硬件 Hardware"], isHot:true },
    { id:"ict002", subject:"ICT", subjectCode:"0417", topic:"硬件 Hardware", difficulty:"medium", type:"single",
      question:"What does CPU stand for? CPU 代表什么？",
      options:["Central Processing Unit 中央处理器","Computer Personal Unit","Central Program Utility","Computer Processing Utility"], answer:0,
      explanation:"CPU = Central Processing Unit 中央处理器，计算机的'大脑'。包含 ALU 算术逻辑单元 + CU 控制单元 + 寄存器 Registers。",
      keywords:["中央处理器 CPU","算术逻辑单元 ALU","控制单元 CU","寄存器 Register","硬件 Hardware"], isHot:true },
    { id:"ict003", subject:"ICT", subjectCode:"0417", topic:"存储 Storage", difficulty:"easy", type:"single",
      question:"Which storage is fastest? 哪个存储最快？",
      options:["HDD 机械硬盘","USB flash drive U盘","SSD 固态硬盘","DVD 光盘"], answer:2,
      explanation:"SSD 固态硬盘 Solid State Drive 无机械部件，用闪存 Flash memory，速度最快。速度排序：SSD > HDD > USB > DVD/CD。",
      keywords:["固态硬盘 SSD","机械硬盘 HDD","闪存 Flash memory","存储 Storage","访问速度 Access speed"], isHot:true },
    { id:"ict004", subject:"ICT", subjectCode:"0417", topic:"存储 Storage", difficulty:"medium", type:"single",
      question:"RAM and ROM difference? RAM 和 ROM 的区别？",
      options:["RAM is read-only; ROM is read-write","RAM is volatile read-write; ROM is non-volatile read-only","Both are the same","RAM is permanent; ROM is temporary"], answer:1,
      explanation:"RAM 随机存取存储器：易失性 Volatile，断电数据丢失，可读可写。ROM 只读存储器：非易失性 Non-volatile，存储启动程序 BIOS。",
      keywords:["随机存取存储器 RAM","只读存储器 ROM","易失性 Volatile","非易失性 Non-volatile","存储 Storage"], isHot:true },
    { id:"ict005", subject:"ICT", subjectCode:"0417", topic:"网络 Network", difficulty:"medium", type:"single",
      question:"What does a router do? 路由器的作用？",
      options:["Increases screen resolution","Connects networks and forwards data packets 连接网络转发数据包","Prints documents","Stores files"], answer:1,
      explanation:"路由器 Router 连接不同网络，根据 IP 地址转发数据包 Forward data packets。家用路由器集成交换机 Switch 和无线接入点 Wireless AP。",
      keywords:["路由器 Router","数据包 Data packet","IP 地址 IP address","网络 Network","转发 Forward"], isHot:true },
    { id:"ict006", subject:"ICT", subjectCode:"0417", topic:"网络 Network", difficulty:"easy", type:"single",
      question:"What does URL stand for? URL 代表什么？",
      options:["Uniform Resource Locator 统一资源定位符","Universal Reference Link","Uniform Reference Language","Universal Resource Link"], answer:0,
      explanation:"URL = Uniform Resource Locator 统一资源定位符，互联网资源地址。如 https://www.example.com/index.html。含协议 Protocol、域名 Domain、路径 Path。",
      keywords:["统一资源定位符 URL","协议 Protocol","域名 Domain","路径 Path","网络 Network"], isHot:true },
    { id:"ict007", subject:"ICT", subjectCode:"0417", topic:"网络 Network", difficulty:"medium", type:"single",
      question:"LAN vs WAN? 局域网和广域网的区别？",
      options:["LAN is larger than WAN","LAN covers small area; WAN covers large area 局域网小范围，广域网大范围","LAN is wireless only; WAN is wired only","They are identical"], answer:1,
      explanation:"LAN 局域网 Local Area Network：小范围（学校/办公室）。WAN 广域网 Wide Area Network：大范围（城市/国家），互联网 Internet 是最大的 WAN。",
      keywords:["局域网 LAN","广域网 WAN","互联网 Internet","网络覆盖范围 Network coverage","拓扑 Topology"], isHot:true },
    { id:"ict008", subject:"ICT", subjectCode:"0417", topic:"数据安全 Security", difficulty:"medium", type:"single",
      question:"What is phishing? 什么是网络钓鱼？",
      options:["A computer virus","Fraudulent attempts to obtain sensitive info by pretending to be trustworthy 伪装可信骗取敏感信息","A method to speed up internet","A type of firewall"], answer:1,
      explanation:"网络钓鱼 Phishing：社会工程攻击 Social engineering，伪装成银行等可信机构，通过邮件/假网站诱骗用户泄露密码、信用卡号等。",
      keywords:["网络钓鱼 Phishing","社会工程 Social engineering","敏感信息 Sensitive information","数据安全 Security","诈骗 Fraud"], isHot:true },
    { id:"ict009", subject:"ICT", subjectCode:"0417", topic:"数据安全 Security", difficulty:"medium", type:"single",
      question:"What is a firewall? 什么是防火墙？",
      options:["A type of virus","A security system controlling network traffic 控制网络流量的安全系统","A storage device","A programming language"], answer:1,
      explanation:"防火墙 Firewall：监控控制进出网络流量，根据规则允许/阻止数据传输。可基于硬件 Hardware 或软件 Software。保护内网免受外部攻击。",
      keywords:["防火墙 Firewall","网络流量 Network traffic","安全规则 Security rule","数据安全 Security","访问控制 Access control"], isHot:true },
    { id:"ict010", subject:"ICT", subjectCode:"0417", topic:"应用软件 Application", difficulty:"easy", type:"single",
      question:"Best for budgets and charts? 最适合做预算和图表的软件？",
      options:["Word processor 文字处理","Spreadsheet 电子表格","Presentation 演示","Database 数据库"], answer:1,
      explanation:"电子表格 Spreadsheet（Excel）最适合数值计算、预算 Budget、图表 Chart。文字处理适合文档，演示适合幻灯片，数据库适合大量结构化数据。",
      keywords:["电子表格 Spreadsheet","预算 Budget","图表 Chart","应用软件 Application","Excel"], isHot:true },
    { id:"ict011", subject:"ICT", subjectCode:"0417", topic:"数据库 Database", difficulty:"hard", type:"single",
      question:"What is a primary key? 什么是主键？",
      options:["The most important field name","A unique identifier for each record 每条记录的唯一标识","The first field in any table","A password to access the database"], answer:1,
      explanation:"主键 Primary Key：唯一标识每条记录，不能重复 Not null + Unique。如学生表的学号 Student ID。外键 Foreign key 引用其他表的主键。",
      keywords:["主键 Primary key","外键 Foreign key","记录 Record","字段 Field","数据库 Database","唯一 Unique"], isHot:true },
    { id:"ict012", subject:"ICT", subjectCode:"0417", topic:"数据库 Database", difficulty:"medium", type:"single",
      question:"What does DBMS stand for? DBMS 代表什么？",
      options:["Database Management System 数据库管理系统","Data Backup and Memory System","Digital Binary Management Software","Database Binary Manipulation System"], answer:0,
      explanation:"DBMS = Database Management System 数据库管理系统，如 MySQL、Oracle、Microsoft Access。用于创建、查询、管理数据库。",
      keywords:["数据库管理系统 DBMS","MySQL","查询 Query","数据库 Database","记录 Record"], isHot:false },
    { id:"ict013", subject:"ICT", subjectCode:"0417", topic:"ICT影响 Impact", difficulty:"hard", type:"single",
      question:"Negative impact of ICT on employment? ICT对就业的负面影响？",
      options:["Increased productivity 生产力提高","Automation causing job losses 自动化导致失业","Better communication 沟通改善","Flexible working 灵活工作"], answer:1,
      explanation:"自动化 Automation 导致制造业、数据录入等行业岗位减少 Job displacement。其他选项是正面影响。ICT 对社会影响是 Paper 1 常考论述题。",
      keywords:["自动化 Automation","失业 Unemployment","ICT影响 Impact","社会 Social","就业 Employment"], isHot:true },
    { id:"ict014", subject:"ICT", subjectCode:"0417", topic:"数据安全 Security", difficulty:"medium", type:"single",
      question:"Backup vs Archive? 备份和归档的区别？",
      options:["They are identical","Backup for recovery; archive for long-term storage 备份用于恢复，归档用于长期存储","Backup only for photos; archive for documents","Archive is temporary; backup is permanent"], answer:1,
      explanation:"备份 Backup：数据副本，用于数据丢失/损坏时恢复 Recovery。归档 Archive：不常用但需保留的数据转移到长期存储，释放主存储空间。3-2-1原则。",
      keywords:["备份 Backup","归档 Archive","数据恢复 Recovery","长期存储 Long-term storage","数据安全 Security"], isHot:true },
    { id:"ict015", subject:"ICT", subjectCode:"0417", topic:"网络 Network", difficulty:"hard", type:"single",
      question:"What is cloud computing? 什么是云计算？",
      options:["Storing files on local hard drive","Using computing resources over the internet 通过互联网使用计算资源","A type of weather forecast software","Computing without electricity"], answer:1,
      explanation:"云计算 Cloud computing：通过互联网按需使用服务器、存储、软件等资源。如 Google Drive、Dropbox、AWS。优点：可扩展 Scalable、按需付费 Pay-as-you-go。",
      keywords:["云计算 Cloud computing","可扩展 Scalable","按需付费 Pay-as-you-go","服务器 Server","存储 Storage"], isHot:true },
    { id:"ict016", subject:"ICT", subjectCode:"0417", topic:"数据表示 Data", difficulty:"medium", type:"single",
      question:"Bitmap vs Vector image? 位图和矢量图的区别？",
      options:["Bitmap is smaller than vector","Bitmap made of pixels; vector made of mathematical formulas 位图由像素组成，矢量图由数学公式描述","Vector loses quality when scaled","Bitmap is always better"], answer:1,
      explanation:"位图 Bitmap/Raster：由像素 Pixel 组成，放大失真 Pixelated，适合照片。矢量图 Vector：由数学公式描述，放大不失真，适合图标 Logo、插图。",
      keywords:["位图 Bitmap","矢量图 Vector","像素 Pixel","分辨率 Resolution","图像 Image","放大 Scale"], isHot:true },
    { id:"ict017", subject:"ICT", subjectCode:"0417", topic:"硬件 Hardware", difficulty:"medium", type:"single",
      question:"What is the function of ALU? ALU 的功能？",
      options:["Controls all operations","Performs arithmetic and logical operations 执行算术和逻辑运算","Stores data permanently","Connects to the internet"], answer:1,
      explanation:"ALU = Arithmetic Logic Unit 算术逻辑单元，执行加减乘除等算术运算 Arithmetic 和 AND/OR/NOT 等逻辑运算 Logical。是 CPU 的组成部分。",
      keywords:["算术逻辑单元 ALU","算术运算 Arithmetic","逻辑运算 Logical","CPU","硬件 Hardware"], isHot:true },
    { id:"ict018", subject:"ICT", subjectCode:"0417", topic:"数据安全 Security", difficulty:"hard", type:"single",
      question:"What is encryption? 什么是加密？",
      options:["Compressing data","Converting data to unreadable format to prevent unauthorised access 将数据转为不可读格式防止未授权访问","Deleting data permanently","Speeding up data transfer"], answer:1,
      explanation:"加密 Encryption：明文 Plaintext 通过算法和密钥 Key 转为密文 Ciphertext。对称加密 Symmetric 用同一密钥，非对称 Asymmetric 用公钥/私钥对 Public/Private key。",
      keywords:["加密 Encryption","明文 Plaintext","密文 Ciphertext","密钥 Key","对称加密 Symmetric","非对称加密 Asymmetric"], isHot:true },
    { id:"ict019", subject:"ICT", subjectCode:"0417", topic:"网络 Network", difficulty:"medium", type:"single",
      question:"What is an IP address? 什么是IP地址？",
      options:["A website name","A unique numerical label for each device on a network 网络中每台设备的唯一数字标识","A type of cable","A password for WiFi"], answer:1,
      explanation:"IP 地址 Internet Protocol address：网络中设备的唯一数字标识，如 192.168.1.1（IPv4）。用于定位和通信。域名 Domain name 是 IP 的易记别名。",
      keywords:["IP 地址 IP address","IPv4","域名 Domain name","网络 Network","唯一标识 Unique identifier"], isHot:false },
    { id:"ict020", subject:"ICT", subjectCode:"0417", topic:"ICT影响 Impact", difficulty:"medium", type:"single",
      question:"What is the digital divide? 什么是数字鸿沟？",
      options:["A type of computer port","Gap between those with and without access to ICT 有无ICT接入者之间的差距","A software error","A type of network cable"], answer:1,
      explanation:"数字鸿沟 Digital divide：不同人群/地区/国家之间在 ICT 接入和使用能力上的差距。影响因素：收入、教育、地理位置、年龄。",
      keywords:["数字鸿沟 Digital divide","接入 Access","不平等 Inequality","ICT影响 Impact","社会 Social"], isHot:true },
    { id:"cs001", subject:"计算机科学", subjectCode:"0478", topic:"数据表示 Data representation", difficulty:"easy", type:"single",
      question:"Convert binary 1011 to decimal. 二进制1011转十进制",
      options:["9","11","13","15"], answer:1,
      explanation:"1011₂ = 1×8 + 0×4 + 1×2 + 1×1 = 11₁₀。从右到左权值：1, 2, 4, 8, 16... Binary to decimal conversion.",
      keywords:["二进制 Binary","十进制 Decimal","位 Bit","权值 Place value","数据表示 Data representation"], isHot:true },
    { id:"cs002", subject:"计算机科学", subjectCode:"0478", topic:"数据表示 Data representation", difficulty:"medium", type:"single",
      question:"Convert decimal 25 to binary. 十进制25转二进制",
      options:["10001","11001","10101","11010"], answer:1,
      explanation:"25÷2=12余1, 12÷2=6余0, 6÷2=3余0, 3÷2=1余1, 1÷2=0余1。从下往上读：11001。验证 16+8+1=25。",
      keywords:["二进制 Binary","十进制 Decimal","转换 Conversion","除2取余 Divide by 2","数据表示 Data representation"], isHot:true },
    { id:"cs003", subject:"计算机科学", subjectCode:"0478", topic:"数据表示 Data representation", difficulty:"easy", type:"single",
      question:"How many bits in a byte? 一字节多少位？",
      options:["4","8","16","32"], answer:1,
      explanation:"1 byte 字节 = 8 bits 位。1 nibble = 4 bits。1 KB = 1024 bytes。1 word 取决于架构（16/32/64 bits）。",
      keywords:["字节 Byte","位 Bit"," nibble 半字节","数据表示 Data representation","存储单位 Storage unit"], isHot:true },
    { id:"cs004", subject:"计算机科学", subjectCode:"0478", topic:"算法 Algorithm", difficulty:"easy", type:"single",
      question:"Time complexity of linear search (worst case)? 线性搜索最坏时间复杂度？",
      options:["O(1)","O(log n)","O(n)","O(n²)"], answer:2,
      explanation:"线性搜索 Linear search 逐个检查，最坏检查全部 n 个元素，O(n)。二分搜索 Binary search O(log n)，但需有序数组 Sorted array。",
      keywords:["线性搜索 Linear search","时间复杂度 Time complexity","大O表示法 Big O notation","算法 Algorithm","搜索 Search"], isHot:true },
    { id:"cs005", subject:"计算机科学", subjectCode:"0478", topic:"算法 Algorithm", difficulty:"medium", type:"single",
      question:"Which sort swaps adjacent elements? 哪个排序交换相邻元素？",
      options:["Insertion sort 插入排序","Bubble sort 冒泡排序","Merge sort 归并排序","Quick sort 快速排序"], answer:1,
      explanation:"冒泡排序 Bubble sort：反复比较相邻元素，顺序错误就交换，每轮将最大元素'冒泡'到末尾。时间复杂度 O(n²)。简单但效率低。",
      keywords:["冒泡排序 Bubble sort","排序 Sorting","时间复杂度 O(n²)","算法 Algorithm","相邻元素 Adjacent"], isHot:true },
    { id:"cs006", subject:"计算机科学", subjectCode:"0478", topic:"编程 Programming", difficulty:"medium", type:"single",
      question:"Output of: x=5; IF x>3 THEN OUTPUT 'Big' ELSE OUTPUT 'Small'",
      options:["Big","Small","5","Error"], answer:0,
      explanation:"x=5，条件 x>3 为真 True，执行 THEN 分支输出 'Big'。IF-THEN-ELSE 选择结构 Selection。",
      keywords:["选择结构 Selection","IF语句 IF statement","条件 Condition","布尔 Boolean","编程 Programming"], isHot:true },
    { id:"cs007", subject:"计算机科学", subjectCode:"0478", topic:"编程 Programming", difficulty:"hard", type:"single",
      question:"Value of sum after: sum=0; FOR i=1 TO 3: sum=sum+i",
      options:["3","6","9","1"], answer:1,
      explanation:"i=1: sum=1; i=2: sum=3; i=3: sum=6。最终 sum=1+2+3=6。FOR 循环 For loop 累加 Accumulation。",
      keywords:["FOR循环 For loop","累加 Accumulation","迭代 Iteration","循环 Loop","编程 Programming"], isHot:true },
    { id:"cs008", subject:"计算机科学", subjectCode:"0478", topic:"硬件 Hardware", difficulty:"medium", type:"single",
      question:"Which gate outputs 1 only when both inputs are 1? 哪个门仅当两输入都为1时输出1？",
      options:["OR gate 或门","AND gate 与门","NOT gate 非门","XOR gate 异或门"], answer:1,
      explanation:"AND 与门：全1出1。真值表 Truth table：00→0, 01→0, 10→0, 11→1。OR 有1出1，NOT 取反，XOR 不同出1。",
      keywords:["逻辑门 Logic gate","AND 与门","真值表 Truth table","硬件 Hardware","布尔逻辑 Boolean logic"], isHot:true },
    { id:"cs009", subject:"计算机科学", subjectCode:"0478", topic:"网络安全 Security", difficulty:"medium", type:"single",
      question:"Purpose of encryption? 加密的目的？",
      options:["Compress data 压缩数据","Convert data to unreadable format to prevent unauthorised access 防止未授权访问","Delete data 永久删除","Speed up transfer 加速传输"], answer:1,
      explanation:"加密 Encryption：明文 Plaintext → 密文 Ciphertext，即使被截获也无法读取。需密钥 Key 解密。对称 Symmetric / 非对称 Asymmetric。",
      keywords:["加密 Encryption","明文 Plaintext","密文 Ciphertext","密钥 Key","网络安全 Security"], isHot:true },
    { id:"cs010", subject:"计算机科学", subjectCode:"0478", topic:"编程 Programming", difficulty:"hard", type:"single",
      question:"What is recursion? 什么是递归？",
      options:["A loop that never ends 无限循环","A function that calls itself with a smaller problem 函数调用自身解决更小问题","A type of variable 变量类型","A programming error 编程错误"], answer:1,
      explanation:"递归 Recursion：函数调用自身解决子问题。必须有基准情形 Base case 终止，否则栈溢出 Stack overflow。经典：阶乘 Factorial、斐波那契 Fibonacci。",
      keywords:["递归 Recursion","基准情形 Base case","函数 Function","栈溢出 Stack overflow","编程 Programming"], isHot:true },
    { id:"cs011", subject:"计算机科学", subjectCode:"0478", topic:"数据表示 Data representation", difficulty:"medium", type:"single",
      question:"What is hexadecimal? 什么是十六进制？",
      options:["Base 2 number system","Base 16 number system using 0-9 and A-F 基数16，用0-9和A-F","Base 10 number system","A type of computer virus"], answer:1,
      explanation:"十六进制 Hexadecimal：基数16，数字 0-9, A-F。4位二进制=1位十六进制，是二进制的紧凑表示。如 FF = 11111111 = 255。常用于内存地址、颜色。",
      keywords:["十六进制 Hexadecimal","基数 Base","A-F","二进制 Binary","数据表示 Data representation"], isHot:true },
    { id:"cs012", subject:"计算机科学", subjectCode:"0478", topic:"算法 Algorithm", difficulty:"hard", type:"single",
      question:"Condition for binary search? 二分搜索的前提条件？",
      options:["Array must be unsorted","Array must be sorted 数组必须有序","Array must be empty","Array must contain numbers only"], answer:1,
      explanation:"二分搜索 Binary search 要求数组已排序 Sorted。每次比较中间元素，排除一半。时间复杂度 O(log n)。线性搜索无需有序但 O(n)。",
      keywords:["二分搜索 Binary search","有序数组 Sorted array","时间复杂度 O(log n)","算法 Algorithm","搜索 Search"], isHot:true },
    { id:"cs013", subject:"计算机科学", subjectCode:"0478", topic:"编程 Programming", difficulty:"medium", type:"single",
      question:"What is a variable? 什么是变量？",
      options:["A fixed value that never changes","A named memory location storing changeable data 命名的内存位置存储可变数据","A type of loop","A programming language"], answer:1,
      explanation:"变量 Variable：命名的内存存储位置，存储程序运行中可改变的值。有数据类型 Data type：整数 Integer、实数 Real、字符 Char、布尔 Boolean、字符串 String。",
      keywords:["变量 Variable","数据类型 Data type","内存 Memory","赋值 Assignment","编程 Programming"], isHot:true },
    { id:"cs014", subject:"计算机科学", subjectCode:"0478", topic:"编程 Programming", difficulty:"hard", type:"single",
      question:"Compiler vs Interpreter? 编译器和解释器的区别？",
      options:["Both translate line by line","Compiler translates whole program then runs; interpreter translates line by line 编译器整体翻译后运行，解释器逐行翻译执行","Compiler is slower","Interpreter creates executable files"], answer:1,
      explanation:"编译器 Compiler：一次性将整个源代码翻译成机器码，生成可执行文件，运行快。解释器 Interpreter：逐行翻译执行，不生成独立文件，便于调试但较慢。",
      keywords:["编译器 Compiler","解释器 Interpreter","源代码 Source code","机器码 Machine code","翻译 Translation"], isHot:true },
    { id:"cs015", subject:"计算机科学", subjectCode:"0478", topic:"硬件 Hardware", difficulty:"medium", type:"single",
      question:"What is the purpose of cache memory? 高速缓存的作用？",
      options:["Permanent storage of files","Temporary high-speed storage for frequently used data 临时高速存储常用数据","Connects to the internet","Displays graphics"], answer:1,
      explanation:"高速缓存 Cache：CPU 内置的高速临时存储器，存储频繁使用的数据和指令，减少从 RAM 读取的等待时间。L1/L2/L3 层级，越小越快越贵。",
      keywords:["高速缓存 Cache","CPU","临时存储 Temporary storage","速度 Speed","硬件 Hardware","内存层次 Memory hierarchy"], isHot:true },
    { id:"cs016", subject:"计算机科学", subjectCode:"0478", topic:"网络 Network", difficulty:"medium", type:"single",
      question:"What does DNS do? DNS的作用？",
      options:["Encrypts data","Translates domain names to IP addresses 将域名翻译为IP地址","Stores emails","Compresses images"], answer:1,
      explanation:"DNS = Domain Name System 域名系统：将易记的域名 Domain name（如 www.example.com）翻译为 IP 地址（如 93.184.216.34）。互联网的'电话簿'。",
      keywords:["域名系统 DNS","域名 Domain name","IP 地址 IP address","解析 Resolution","网络 Network"], isHot:true },
    { id:"cs017", subject:"计算机科学", subjectCode:"0478", topic:"算法 Algorithm", difficulty:"hard", type:"single",
      question:"Average time complexity of quick sort? 快速排序平均时间复杂度？",
      options:["O(n)","O(n log n)","O(n²)","O(log n)"], answer:1,
      explanation:"快速排序 Quick sort：选基准 Pivot，分区 Partition 后递归。平均 O(n log n)，最坏 O(n²)（已排序数据）。实际应用中最快的通用排序之一。",
      keywords:["快速排序 Quick sort","基准 Pivot","分区 Partition","时间复杂度 Time complexity","算法 Algorithm"], isHot:true },
    { id:"cs018", subject:"计算机科学", subjectCode:"0478", topic:"数据结构 Data structure", difficulty:"medium", type:"single",
      question:"What is an array? 什么是数组？",
      options:["A single variable","A collection of elements of the same type stored contiguously 相同类型元素的连续集合","A type of loop","A programming language"], answer:1,
      explanation:"数组 Array：相同数据类型元素的有序集合，连续存储，通过索引 Index 访问（从0开始）。优点：随机访问 O(1)。缺点：大小固定，插入删除慢。",
      keywords:["数组 Array","索引 Index","元素 Element","数据结构 Data structure","连续存储 Contiguous"], isHot:true },
    { id:"cs019", subject:"计算机科学", subjectCode:"0478", topic:"编程 Programming", difficulty:"medium", type:"single",
      question:"What is a loop used for? 循环的用途？",
      options:["Making decisions","Repeating a block of code multiple times 重复执行代码块","Storing data","Connecting to network"], answer:1,
      explanation:"循环 Loop/Iteration：重复执行代码块。FOR 循环（已知次数）、WHILE 循环（条件控制）、REPEAT-UNTIL（至少执行一次）。避免重复代码。",
      keywords:["循环 Loop","迭代 Iteration","FOR循环","WHILE循环","重复 Repetition","编程 Programming"], isHot:true },
    { id:"cs020", subject:"计算机科学", subjectCode:"0478", topic:"网络安全 Security", difficulty:"hard", type:"single",
      question:"What is a DDoS attack? 什么是DDoS攻击？",
      options:["A type of virus","Distributed Denial of Service - overwhelming a server with traffic from many sources 分布式拒绝服务攻击","A method to speed up websites","A type of encryption"], answer:1,
      explanation:"DDoS = Distributed Denial of Service 分布式拒绝服务：从多个来源（僵尸网络 Botnet）向目标服务器发送大量请求，使其无法响应正常用户。防御：CDN、流量过滤。",
      keywords:["DDoS 分布式拒绝服务","僵尸网络 Botnet","服务器 Server","流量 Traffic","网络安全 Security","攻击 Attack"], isHot:true },
];
