const QUESTIONS_PART1 = [
    { id:"m001", subject:"数学", subjectCode:"0580", topic:"代数 Algebra", difficulty:"easy", type:"single",
      question:"解方程：2x + 5 = 13，x 的值是多少？Solve: 2x + 5 = 13",
      options:["x = 3","x = 4","x = 5","x = 9"], answer:1,
      explanation:"两边减5得 2x = 8，除以2得 x = 4。Subtract 5, divide by 2.",
      keywords:["方程 Equation","代数 Algebra","未知数 Unknown"], isHot:true },
    { id:"m002", subject:"数学", subjectCode:"0580", topic:"代数 Algebra", difficulty:"medium", type:"single",
      question:"因式分解：x² - 9。Factorise: x² - 9",
      options:["(x-3)(x-3)","(x+3)(x+3)","(x-3)(x+3)","(x-9)(x+1)"], answer:2,
      explanation:"平方差公式 Difference of squares: a²-b²=(a-b)(a+b)，所以 x²-9=(x-3)(x+3)。",
      keywords:["因式分解 Factorise","平方差 Difference of squares","代数 Algebra"], isHot:true },
    { id:"m003", subject:"数学", subjectCode:"0580", topic:"几何 Geometry", difficulty:"easy", type:"single",
      question:"圆的半径是 7cm，面积是多少？(π=22/7) Area of circle radius 7cm?",
      options:["44 cm²","154 cm²","308 cm²","49 cm²"], answer:1,
      explanation:"面积 Area = πr² = (22/7)×49 = 154 cm²。",
      keywords:["圆 Circle","面积 Area","半径 Radius","π Pi"], isHot:true },
    { id:"m004", subject:"数学", subjectCode:"0580", topic:"几何 Geometry", difficulty:"medium", type:"single",
      question:"三角形三内角比 2:3:4，最大角多少度？Largest angle of triangle with ratio 2:3:4?",
      options:["40°","60°","80°","100°"], answer:2,
      explanation:"内角和 180°，9x=180，x=20，最大角=4x=80°。Angles sum to 180°.",
      keywords:["三角形 Triangle","内角 Interior angle","比例 Ratio"], isHot:false },
    { id:"m005", subject:"数学", subjectCode:"0580", topic:"数与运算 Number", difficulty:"easy", type:"single",
      question:"计算：(-3) × (-4) + (-5)",
      options:["7","-7","17","-17"], answer:0,
      explanation:"负负得正 Negative×negative=positive：(-3)×(-4)=12，12-5=7。",
      keywords:["负数 Negative number","运算 Operation","乘法 Multiplication"], isHot:false },
    { id:"m006", subject:"数学", subjectCode:"0580", topic:"概率统计 Probability", difficulty:"medium", type:"single",
      question:"袋中有3红5蓝球，取红球概率？Probability of red from 3 red, 5 blue?",
      options:["3/5","3/8","5/8","1/2"], answer:1,
      explanation:"总球数 8，红球概率=3/8。Probability = favourable/total.",
      keywords:["概率 Probability","随机 Random","分数 Fraction"], isHot:true },
    { id:"m007", subject:"数学", subjectCode:"0580", topic:"代数 Algebra", difficulty:"hard", type:"single",
      question:"解二次方程 x² - 5x + 6 = 0。Solve quadratic equation",
      options:["x=1, x=6","x=2, x=3","x=-2, x=-3","x=1, x=5"], answer:1,
      explanation:"因式分解 (x-2)(x-3)=0，所以 x=2 或 x=3。Factorise to find roots.",
      keywords:["二次方程 Quadratic equation","因式分解 Factorise","根 Root"], isHot:true },
    { id:"m008", subject:"数学", subjectCode:"0580", topic:"函数 Function", difficulty:"medium", type:"single",
      question:"f(x) = 3x - 2，求 f(4)",
      options:["10","12","14","8"], answer:0,
      explanation:"f(4)=3×4-2=12-2=10。Substitute x=4.",
      keywords:["函数 Function","代入 Substitution","求值 Evaluate"], isHot:false },
    { id:"m009", subject:"数学", subjectCode:"0580", topic:"三角函数 Trigonometry", difficulty:"medium", type:"single",
      question:"直角三角形中，对边=3，斜边=5，sinθ=？sinθ = opposite/hypotenuse = ?",
      options:["3/5","4/5","3/4","5/3"], answer:0,
      explanation:"sinθ = 对边/斜边 = 3/5。SOH: Sin=Opposite/Hypotenuse.",
      keywords:["三角函数 Trigonometry","正弦 Sine","直角三角形 Right triangle","斜边 Hypotenuse"], isHot:true },
    { id:"m010", subject:"数学", subjectCode:"0580", topic:"比例与百分比 Percent", difficulty:"easy", type:"single",
      question:"一件商品原价 $80，打 25% 折扣后价格？Price after 25% discount on $80?",
      options:["$55","$60","$65","$75"], answer:1,
      explanation:"折扣=80×25%=20，折后价=80-20=$60。Discount = 80×0.25=20.",
      keywords:["百分比 Percentage","折扣 Discount","比例 Ratio"], isHot:true },
    { id:"m011", subject:"数学", subjectCode:"0580", topic:"代数 Algebra", difficulty:"medium", type:"single",
      question:"化简：(2x³)²。Simplify (2x³)²",
      options:["4x⁶","4x⁵","2x⁶","4x⁹"], answer:0,
      explanation:"(2x³)² = 2² × (x³)² = 4x⁶。Power of a product rule.",
      keywords:["指数 Index/Exponent","化简 Simplify","代数 Algebra"], isHot:false },
    { id:"m012", subject:"数学", subjectCode:"0580", topic:"几何 Geometry", difficulty:"medium", type:"single",
      question:"圆柱底面半径 3cm，高 10cm，体积？Volume of cylinder r=3, h=10?",
      options:["90π cm³","30π cm³","60π cm³","180π cm³"], answer:0,
      explanation:"圆柱体积 Volume = πr²h = π×9×10 = 90π cm³。",
      keywords:["圆柱 Cylinder","体积 Volume","半径 Radius","高 Height"], isHot:true },
    { id:"m013", subject:"数学", subjectCode:"0580", topic:"数列 Sequence", difficulty:"medium", type:"single",
      question:"数列 2, 5, 8, 11, ... 第10项是？10th term of sequence 2,5,8,11...?",
      options:["29","30","31","32"], answer:0,
      explanation:"等差数列 Arithmetic sequence，公差 d=3，第n项=2+(n-1)×3=3n-1，第10项=29。",
      keywords:["数列 Sequence","等差数列 Arithmetic","公差 Common difference"], isHot:false },
    { id:"m014", subject:"数学", subjectCode:"0580", topic:"概率统计 Probability", difficulty:"hard", type:"single",
      question:"掷两个骰子，点数和为7的概率？Probability sum=7 with two dice?",
      options:["1/6","1/12","5/36","7/36"], answer:0,
      explanation:"总组合 36，和为7的组合：(1,6)(2,5)(3,4)(4,3)(5,2)(6,1)=6种，概率=6/36=1/6。",
      keywords:["概率 Probability","骰子 Dice","组合 Combination"], isHot:true },
    { id:"m015", subject:"数学", subjectCode:"0580", topic:"函数 Function", difficulty:"hard", type:"single",
      question:"求 y = x² - 4x + 3 的顶点坐标。Vertex of y = x² - 4x + 3?",
      options:["(2, -1)","(2, 1)","(-2, -1)","(4, 3)"], answer:0,
      explanation:"顶点 x = -b/2a = 4/2 = 2，y = 4-8+3 = -1，顶点(2,-1)。Complete the square.",
      keywords:["二次函数 Quadratic function","顶点 Vertex","抛物线 Parabola"], isHot:true },
    { id:"p001", subject:"物理", subjectCode:"0625", topic:"力学 Mechanics", difficulty:"easy", type:"single",
      question:"5kg 物体受 20N 合力，加速度？Acceleration of 5kg mass with 20N force?",
      options:["2 m/s²","4 m/s²","100 m/s²","0.25 m/s²"], answer:1,
      explanation:"牛顿第二定律 Newton's 2nd Law: F=ma，a=F/m=20/5=4 m/s²。",
      keywords:["牛顿第二定律 Newton's 2nd Law","力 Force","质量 Mass","加速度 Acceleration"], isHot:true },
    { id:"p002", subject:"物理", subjectCode:"0625", topic:"力学 Mechanics", difficulty:"medium", type:"single",
      question:"2kg 物体以 3m/s 运动，动能？Kinetic energy of 2kg at 3m/s?",
      options:["6 J","9 J","18 J","3 J"], answer:1,
      explanation:"动能 KE = ½mv² = ½×2×9 = 9 J。",
      keywords:["动能 Kinetic energy","质量 Mass","速度 Velocity","焦耳 Joule"], isHot:true },
    { id:"p003", subject:"物理", subjectCode:"0625", topic:"电学 Electricity", difficulty:"easy", type:"single",
      question:"电压 6V，电阻 3Ω，电流？Current with V=6V, R=3Ω?",
      options:["2 A","18 A","0.5 A","9 A"], answer:0,
      explanation:"欧姆定律 Ohm's Law: V=IR，I=V/R=6/3=2 A。",
      keywords:["欧姆定律 Ohm's Law","电压 Voltage","电流 Current","电阻 Resistance"], isHot:true },
    { id:"p004", subject:"物理", subjectCode:"0625", topic:"热学 Thermal", difficulty:"medium", type:"single",
      question:"水的比热容 4200 J/(kg·°C)，2kg 水升温 10°C 需多少热量？Heat to raise 2kg water by 10°C?",
      options:["42000 J","84000 J","21000 J","8400 J"], answer:1,
      explanation:"Q = mcΔT = 2×4200×10 = 84000 J。Specific heat capacity formula.",
      keywords:["比热容 Specific heat capacity","热量 Heat energy","温度 Temperature"], isHot:true },
    { id:"p005", subject:"物理", subjectCode:"0625", topic:"波 Waves", difficulty:"easy", type:"single",
      question:"波速 340m/s，频率 170Hz，波长？Wavelength when v=340m/s, f=170Hz?",
      options:["2 m","0.5 m","57800 m","20 m"], answer:0,
      explanation:"v = fλ，λ = v/f = 340/170 = 2 m。Wave speed formula.",
      keywords:["波速 Wave speed","频率 Frequency","波长 Wavelength","振幅 Amplitude"], isHot:true },
    { id:"p006", subject:"物理", subjectCode:"0625", topic:"力学 Mechanics", difficulty:"medium", type:"single",
      question:"物体从 10m 高处自由下落，落地速度？(g=10m/s²) Velocity after falling 10m?",
      options:["10 m/s","14.1 m/s","20 m/s","100 m/s"], answer:1,
      explanation:"v² = u² + 2as = 0 + 2×10×10 = 200，v = √200 ≈ 14.1 m/s。Kinematics equation.",
      keywords:["自由落体 Free fall","重力加速度 Gravitational acceleration","运动学 Kinematics"], isHot:false },
    { id:"p007", subject:"物理", subjectCode:"0625", topic:"电学 Electricity", difficulty:"medium", type:"single",
      question:"两个 4Ω 电阻并联，总电阻？Total resistance of two 4Ω in parallel?",
      options:["8 Ω","4 Ω","2 Ω","1 Ω"], answer:2,
      explanation:"并联 Parallel: 1/R = 1/4+1/4 = 1/2，R = 2Ω。相同电阻并联 R/n。",
      keywords:["并联 Parallel","电阻 Resistance","电路 Circuit"], isHot:true },
    { id:"p008", subject:"物理", subjectCode:"0625", topic:"光学 Light", difficulty:"easy", type:"single",
      question:"光从空气进入玻璃，会发生什么？What happens when light enters glass from air?",
      options:["速度增加，向法线偏折","速度减小，向法线偏折","速度不变，不偏折","速度减小，远离法线"], answer:1,
      explanation:"光在光密介质中速度减小，折射角小于入射角，向法线偏折。Refraction towards normal.",
      keywords:["折射 Refraction","法线 Normal","光密介质 Denser medium","入射角 Incident angle"], isHot:true },
    { id:"p009", subject:"物理", subjectCode:"0625", topic:"力学 Mechanics", difficulty:"hard", type:"single",
      question:"功率 1000W 的机器在 5s 内做多少功？Work done by 1000W machine in 5s?",
      options:["200 J","5000 J","1005 J","500 J"], answer:1,
      explanation:"功率 Power = Work/time，W = Pt = 1000×5 = 5000 J。",
      keywords:["功率 Power","功 Work","时间 Time","瓦特 Watt"], isHot:false },
    { id:"p010", subject:"物理", subjectCode:"0625", topic:"热学 Thermal", difficulty:"medium", type:"single",
      question:"热传递的三种方式是？Three methods of heat transfer?",
      options:["传导、对流、辐射","传导、蒸发、凝结","对流、辐射、升华","传导、对流、蒸发"], answer:0,
      explanation:"热传递三方式：传导 Conduction（固体）、对流 Convection（流体）、辐射 Radiation（不需介质）。",
      keywords:["热传导 Conduction","热对流 Convection","热辐射 Radiation","热传递 Heat transfer"], isHot:true },
    { id:"p011", subject:"物理", subjectCode:"0625", topic:"电学 Electricity", difficulty:"hard", type:"single",
      question:"220V 100W 灯泡正常工作时电阻？Resistance of 220V 100W bulb?",
      options:["484 Ω","2.2 Ω","22000 Ω","0.45 Ω"], answer:0,
      explanation:"P = V²/R，R = V²/P = 220²/100 = 48400/100 = 484 Ω。",
      keywords:["电功率 Power","电压 Voltage","电阻 Resistance","灯泡 Bulb"], isHot:true },
    { id:"p012", subject:"物理", subjectCode:"0625", topic:"波 Waves", difficulty:"medium", type:"single",
      question:"电磁波谱中，频率最高的是？Highest frequency in electromagnetic spectrum?",
      options:["无线电波","红外线","紫外线","伽马射线"], answer:3,
      explanation:"电磁波谱频率从低到高：无线电→微波→红外→可见光→紫外→X射线→伽马射线 Gamma rays。",
      keywords:["电磁波 Electromagnetic wave","频率 Frequency","伽马射线 Gamma ray","光谱 Spectrum"], isHot:true },
    { id:"p013", subject:"物理", subjectCode:"0625", topic:"力学 Mechanics", difficulty:"easy", type:"single",
      question:"密度公式是？Density formula?",
      options:["ρ = m/V","ρ = V/m","ρ = m×V","ρ = m/V²"], answer:0,
      explanation:"密度 Density = 质量 Mass / 体积 Volume，单位 kg/m³ 或 g/cm³。",
      keywords:["密度 Density","质量 Mass","体积 Volume"], isHot:false },
    { id:"p014", subject:"物理", subjectCode:"0625", topic:"光学 Light", difficulty:"medium", type:"single",
      question:"凸透镜对光线的作用是？Convex lens effect on light?",
      options:["发散","会聚","反射","吸收"], answer:1,
      explanation:"凸透镜 Convex lens 会聚光线 Converging，凹透镜 Diverging lens 发散光线。",
      keywords:["凸透镜 Convex lens","会聚 Converge","焦点 Focal point","折射 Refraction"], isHot:false },
    { id:"p015", subject:"物理", subjectCode:"0625", topic:"力学 Mechanics", difficulty:"hard", type:"single",
      question:"动量公式是？Momentum formula?",
      options:["p = mv","p = ma","p = F/t","p = ½mv²"], answer:0,
      explanation:"动量 Momentum = 质量×速度 = mv，单位 kg·m/s。动量守恒 Conservation of momentum 是常考点。",
      keywords:["动量 Momentum","质量 Mass","速度 Velocity","动量守恒 Conservation"], isHot:true },
    { id:"c001", subject:"化学", subjectCode:"0620", topic:"原子结构 Atomic structure", difficulty:"easy", type:"single",
      question:"原子序数等于？Atomic number equals?",
      options:["中子数","质子数","电子数+中子数","质量数"], answer:1,
      explanation:"原子序数 Atomic number = 质子数 Proton number = 中性原子电子数。质量数 Mass number = 质子+中子。",
      keywords:["原子序数 Atomic number","质子 Proton","中子 Neutron","电子 Electron"], isHot:true },
    { id:"c002", subject:"化学", subjectCode:"0620", topic:"化学键 Bonding", difficulty:"medium", type:"single",
      question:"NaCl 中存在的化学键是？Bond in NaCl?",
      options:["共价键","离子键","金属键","氢键"], answer:1,
      explanation:"NaCl 是金属+非金属，通过电子转移形成离子键 Ionic bond。Na⁺ 和 Cl⁻ 静电吸引。",
      keywords:["离子键 Ionic bond","共价键 Covalent bond","金属键 Metallic bond","电子转移 Electron transfer"], isHot:true },
    { id:"c003", subject:"化学", subjectCode:"0620", topic:"酸碱 Acids & bases", difficulty:"easy", type:"single",
      question:"pH = 1 的溶液呈？Solution with pH=1 is?",
      options:["强酸性","弱酸性","中性","碱性"], answer:0,
      explanation:"pH<7 酸性 Acidic，pH 越小酸性越强。pH=1 是强酸 Strong acid。pH=7 中性 Neutral。",
      keywords:["pH 值 pH","酸 Acid","碱 Base","中性 Neutral","指示剂 Indicator"], isHot:true },
    { id:"c004", subject:"化学", subjectCode:"0620", topic:"化学反应 Reaction", difficulty:"medium", type:"single",
      question:"催化剂的作用是？Catalyst does what?",
      options:["增加产物质量","改变反应速率，本身不变","增加反应热","改变反应方向"], answer:1,
      explanation:"催化剂 Catalyst 改变反应速率（通常加快），降低活化能 Activation energy，反应前后质量和化学性质不变。",
      keywords:["催化剂 Catalyst","活化能 Activation energy","反应速率 Reaction rate"], isHot:true },
    { id:"c005", subject:"化学", subjectCode:"0620", topic:"氧化还原 Redox", difficulty:"medium", type:"single",
      question:"下列哪个是氧化反应？Which is oxidation?",
      options:["Cu²⁺ + 2e⁻ → Cu","Zn → Zn²⁺ + 2e⁻","O₂ + 4e⁻ → 2O²⁻","Fe³⁺ + e⁻ → Fe²⁺"], answer:1,
      explanation:"氧化 Oxidation = 失电子 Loss of electrons（OIL）。Zn 失去电子变成 Zn²⁺。还原 Reduction = 得电子（RIG）。",
      keywords:["氧化 Oxidation","还原 Reduction","电子 Electron","氧化还原 Redox"], isHot:true },
    { id:"c006", subject:"化学", subjectCode:"0620", topic:"有机化学 Organic", difficulty:"medium", type:"single",
      question:"甲烷的分子式是？Molecular formula of methane?",
      options:["CH₄","C₂H₆","C₂H₄","CH₃"], answer:0,
      explanation:"甲烷 Methane 是最简单的烷烃 Alkane，分子式 CH₄，正四面体结构。烷烃通式 CₙH₂ₙ₊₂。",
      keywords:["甲烷 Methane","烷烃 Alkane","有机化学 Organic","烃 Hydrocarbon"], isHot:true },
    { id:"c007", subject:"化学", subjectCode:"0620", topic:"原子结构 Atomic structure", difficulty:"easy", type:"single",
      question:"同位素是指？Isotopes are?",
      options:["质子数不同，中子数相同","质子数相同，中子数不同","电子数不同","质量数相同"], answer:1,
      explanation:"同位素 Isotopes：质子数相同但中子数不同的同一元素的原子，化学性质相同，物理性质不同。",
      keywords:["同位素 Isotope","质子 Proton","中子 Neutron","元素 Element"], isHot:true },
    { id:"c008", subject:"化学", subjectCode:"0620", topic:"酸碱 Acids & bases", difficulty:"medium", type:"single",
      question:"中和反应的产物是？Products of neutralisation?",
      options:["酸+碱","盐+水","盐+氧气","水+二氧化碳"], answer:1,
      explanation:"中和反应 Neutralisation：酸 + 碱 → 盐 + 水。Acid + Base → Salt + Water。",
      keywords:["中和 Neutralisation","盐 Salt","水 Water","酸 Acid","碱 Base"], isHot:true },
    { id:"c009", subject:"化学", subjectCode:"0620", topic:"化学反应 Reaction", difficulty:"hard", type:"single",
      question:"平衡系统中增加反应物浓度，平衡如何移动？Increase reactant concentration, equilibrium shifts?",
      options:["正向移动","逆向移动","不移动","无法判断"], answer:0,
      explanation:"勒夏特列原理 Le Chatelier's Principle：平衡向减弱改变的方向移动。增加反应物→正向移动消耗反应物。",
      keywords:["化学平衡 Equilibrium","勒夏特列原理 Le Chatelier","浓度 Concentration","可逆反应 Reversible"], isHot:true },
    { id:"c010", subject:"化学", subjectCode:"0620", topic:"化学键 Bonding", difficulty:"medium", type:"single",
      question:"H₂O 中 O 和 H 之间的键是？Bond between O and H in water?",
      options:["离子键","共价键","金属键","范德华力"], answer:1,
      explanation:"H₂O 中 O-H 是共价键 Covalent bond（共用电子对）。水分子间存在氢键 Hydrogen bond。",
      keywords:["共价键 Covalent bond","氢键 Hydrogen bond","水 Water","共用电子对 Shared pair"], isHot:false },
    { id:"c011", subject:"化学", subjectCode:"0620", topic:"有机化学 Organic", difficulty:"hard", type:"single",
      question:"乙烯使溴水褪色是因为发生了？Ethene decolourises bromine water due to?",
      options:["取代反应","加成反应","氧化反应","还原反应"], answer:1,
      explanation:"乙烯 Ethene 含碳碳双键 C=C，与溴发生加成反应 Addition reaction，使溴水褪色。这是检验不饱和烃的方法。",
      keywords:["加成反应 Addition","双键 Double bond","乙烯 Ethene","溴水 Bromine water","不饱和 Unsaturated"], isHot:true },
    { id:"c012", subject:"化学", subjectCode:"0620", topic:"化学反应 Reaction", difficulty:"easy", type:"single",
      question:"碳酸钙加热分解的产物是？Thermal decomposition of calcium carbonate?",
      options:["CaO + CO₂","Ca + CO₂","CaO + O₂","Ca(OH)₂ + CO₂"], answer:0,
      explanation:"CaCO₃ →(加热)→ CaO + CO₂。石灰石煅烧生产生石灰 Quicklime。这是吸热反应 Endothermic。",
      keywords:["热分解 Thermal decomposition","碳酸钙 Calcium carbonate","二氧化碳 Carbon dioxide","吸热 Endothermic"], isHot:true },
    { id:"c013", subject:"化学", subjectCode:"0620", topic:"氧化还原 Redox", difficulty:"hard", type:"single",
      question:"在反应 2Mg + O₂ → 2MgO 中，Mg 被？In this reaction Mg is?",
      options:["被还原","被氧化","催化剂","溶剂"], answer:1,
      explanation:"Mg 从 0 价升到 +2 价，失去电子，被氧化 Oxidised，是还原剂 Reducing agent。O₂ 被还原。",
      keywords:["氧化 Oxidation","还原 Reduction","还原剂 Reducing agent","化合价 Oxidation state"], isHot:false },
    { id:"c014", subject:"化学", subjectCode:"0620", topic:"酸碱 Acids & bases", difficulty:"hard", type:"single",
      question:"强酸与弱酸的区别是？Strong vs weak acid difference?",
      options:["pH 值不同","电离程度不同","浓度不同","颜色不同"], answer:1,
      explanation:"强酸 Strong acid 在水中完全电离 Fully ionised（如 HCl）。弱酸 Weak acid 部分电离 Partially ionised（如 CH₃COOH）。注意与浓度区分。",
      keywords:["强酸 Strong acid","弱酸 Weak acid","电离 Ionisation","浓度 Concentration"], isHot:true },
    { id:"c015", subject:"化学", subjectCode:"0620", topic:"原子结构 Atomic structure", difficulty:"medium", type:"single",
      question:"电子排布 2,8,8 的元素是？Element with electron arrangement 2,8,8?",
      options:["氧","氖","氩","氯"], answer:2,
      explanation:"电子总数=18，原子序数18，是氩 Argon（稀有气体 Noble gas）。最外层8电子稳定结构 Octet。",
      keywords:["电子排布 Electron arrangement","稀有气体 Noble gas","稳定结构 Stable octet","氩 Argon"], isHot:false },
    { id:"b001", subject:"生物", subjectCode:"0610", topic:"细胞 Cell", difficulty:"easy", type:"single",
      question:"植物细胞有而动物细胞没有的结构是？Plant cells have but animal cells don't?",
      options:["细胞核","细胞膜","细胞壁","核糖体"], answer:2,
      explanation:"植物细胞特有：细胞壁 Cell wall（纤维素）、叶绿体 Chloroplast、液泡 Vacuole。动物细胞没有这些。",
      keywords:["细胞壁 Cell wall","叶绿体 Chloroplast","液泡 Vacuole","植物细胞 Plant cell"], isHot:true },
    { id:"b002", subject:"生物", subjectCode:"0610", topic:"光合作用 Photosynthesis", difficulty:"medium", type:"single",
      question:"光合作用的场所是？Site of photosynthesis?",
      options:["线粒体","叶绿体","细胞核","核糖体"], answer:1,
      explanation:"光合作用在叶绿体 Chloroplast 中进行，含叶绿素 Chlorophyll 吸收光能。线粒体 Mitochondria 是呼吸作用场所。",
      keywords:["光合作用 Photosynthesis","叶绿体 Chloroplast","叶绿素 Chlorophyll","光能 Light energy"], isHot:true },
    { id:"b003", subject:"生物", subjectCode:"0610", topic:"遗传 Genetics", difficulty:"medium", type:"single",
      question:"DNA 碱基配对规则是？DNA base pairing rule?",
      options:["A-G, T-C","A-T, G-C","A-C, G-T","A-A, T-T"], answer:1,
      explanation:"A-T（腺嘌呤 Adenine-胸腺嘧啶 Thymine），G-C（鸟嘌呤 Guanine-胞嘧啶 Cytosine）。A-T 之间2个氢键，G-C 之间3个。",
      keywords:["DNA","碱基对 Base pair","腺嘌呤 Adenine","胸腺嘧啶 Thymine","鸟嘌呤 Guanine","胞嘧啶 Cytosine"], isHot:true },
    { id:"b004", subject:"生物", subjectCode:"0610", topic:"酶 Enzyme", difficulty:"easy", type:"single",
      question:"酶的本质是？Enzymes are?",
      options:["糖类","蛋白质","脂质","核酸"], answer:1,
      explanation:"酶 Enzyme 是生物催化剂 Biological catalyst，本质是蛋白质 Protein。具有专一性 Specificity、高效性，受温度和 pH 影响。",
      keywords:["酶 Enzyme","蛋白质 Protein","催化剂 Catalyst","专一性 Specificity","活性位点 Active site"], isHot:true },
    { id:"b005", subject:"生物", subjectCode:"0610", topic:"呼吸作用 Respiration", difficulty:"medium", type:"single",
      question:"有氧呼吸的总反应式是？Aerobic respiration equation?",
      options:["C₆H₁₂O₆ + O₂ → CO₂ + H₂O","C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + 能量","6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂","C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂"], answer:1,
      explanation:"有氧呼吸 Aerobic respiration：葡萄糖+氧气→二氧化碳+水+能量。在线粒体中进行，释放大量能量。",
      keywords:["有氧呼吸 Aerobic respiration","葡萄糖 Glucose","线粒体 Mitochondria","能量 ATP"], isHot:true },
    { id:"b006", subject:"生物", subjectCode:"0610", topic:"遗传 Genetics", difficulty:"hard", type:"single",
      question:"双眼皮(A)对单眼皮(a)显性，父母都是 Aa，孩子单眼皮概率？Probability of aa child from Aa×Aa?",
      options:["0%","25%","50%","75%"], answer:1,
      explanation:"Aa×Aa 后代：AA(25%)、Aa(50%)、aa(25%)。单眼皮 aa 概率 25%。庞尼特方格 Punnett square。",
      keywords:["遗传 Genetics","显性 Dominant","隐性 Recessive","等位基因 Allele","庞尼特方格 Punnett square"], isHot:true },
    { id:"b007", subject:"生物", subjectCode:"0610", topic:"细胞 Cell", difficulty:"medium", type:"single",
      question:"控制物质进出细胞的结构是？Controls what enters/leaves cell?",
      options:["细胞壁","细胞膜","细胞核","细胞质"], answer:1,
      explanation:"细胞膜 Cell membrane 具有选择透过性 Selectively permeable，控制物质进出。细胞壁全透性，起支持保护作用。",
      keywords:["细胞膜 Cell membrane","选择透过性 Selectively permeable","扩散 Diffusion","渗透 Osmosis"], isHot:true },
    { id:"b008", subject:"生物", subjectCode:"0610", topic:"人体 Human", difficulty:"easy", type:"single",
      question:"血液中运输氧气的细胞是？Blood cell that transports oxygen?",
      options:["白细胞","红细胞","血小板","血浆"], answer:1,
      explanation:"红细胞 Red blood cell 含血红蛋白 Haemoglobin，运输氧气。白细胞 White blood cell 免疫，血小板 Platelet 凝血。",
      keywords:["红细胞 Red blood cell","血红蛋白 Haemoglobin","氧气 Oxygen","血液 Blood"], isHot:true },
    { id:"b009", subject:"生物", subjectCode:"0610", topic:"植物 Plant", difficulty:"medium", type:"single",
      question:"植物运输水分的组织是？Tissue that transports water in plants?",
      options:["韧皮部","木质部","形成层","表皮"], answer:1,
      explanation:"木质部 Xylem 运输水分和无机盐（从根到叶）。韧皮部 Phloem 运输有机物（如蔗糖）。蒸腾作用 Transpiration 提供拉力。",
      keywords:["木质部 Xylem","韧皮部 Phloem","蒸腾作用 Transpiration","水分 Water","植物 Plant"], isHot:true },
    { id:"b010", subject:"生物", subjectCode:"0610", topic:"生态 Ecosystem", difficulty:"easy", type:"single",
      question:"食物链中能量传递效率约为？Energy transfer efficiency in food chain?",
      options:["1%","10%","50%","90%"], answer:1,
      explanation:"能量在食物链中逐级递减，每级约传递 10%（10% Rule）。大部分能量通过呼吸作用以热能散失。",
      keywords:["食物链 Food chain","能量传递 Energy transfer","营养级 Trophic level","生产者 Producer","消费者 Consumer"], isHot:true },
    { id:"b011", subject:"生物", subjectCode:"0610", topic:"细胞分裂 Cell division", difficulty:"hard", type:"single",
      question:"产生生殖细胞的分裂方式是？Cell division producing gametes?",
      options:["有丝分裂","减数分裂","无丝分裂","二分裂"], answer:1,
      explanation:"减数分裂 Meiosis 产生染色体数目减半的生殖细胞 Gamete（精子/卵子）。有丝分裂 Mitosis 产生相同子细胞，用于生长修复。",
      keywords:["减数分裂 Meiosis","有丝分裂 Mitosis","生殖细胞 Gamete","染色体 Chromosome"], isHot:true },
    { id:"b012", subject:"生物", subjectCode:"0610", topic:"酶 Enzyme", difficulty:"medium", type:"single",
      question:"温度过高时酶会？Enzyme at too high temperature?",
      options:["活性增强","变性失活","不变","复制"], answer:1,
      explanation:"高温破坏酶的空间结构，导致变性 Denaturation，永久失活。低温只是抑制活性，升温可恢复。最适温度 Optimum temperature。",
      keywords:["变性 Denaturation","最适温度 Optimum temperature","活性 Activity","酶 Enzyme"], isHot:true },
    { id:"b013", subject:"生物", subjectCode:"0610", topic:"人体 Human", difficulty:"medium", type:"single",
      question:"人体消化淀粉的起始部位是？Where starch digestion begins?",
      options:["胃","小肠","口腔","大肠"], answer:2,
      explanation:"口腔 Oral cavity 中唾液淀粉酶 Salivary amylase 开始消化淀粉。胃消化蛋白质，小肠是主要消化吸收场所。",
      keywords:["消化 Digestion","淀粉酶 Amylase","淀粉 Starch","口腔 Oral cavity","小肠 Small intestine"], isHot:false },
    { id:"b014", subject:"生物", subjectCode:"0610", topic:"遗传 Genetics", difficulty:"medium", type:"single",
      question:"基因的本质是？Genes are made of?",
      options:["蛋白质","DNA 片段","RNA","糖类"], answer:1,
      explanation:"基因 Gene 是 DNA 上具有遗传效应的片段，控制生物性状。染色体 Chromosome 由 DNA 和蛋白质组成。",
      keywords:["基因 Gene","DNA","染色体 Chromosome","遗传 Heredity","性状 Characteristic"], isHot:true },
    { id:"b015", subject:"生物", subjectCode:"0610", topic:"呼吸作用 Respiration", difficulty:"hard", type:"single",
      question:"无氧呼吸在人体中产生？Anaerobic respiration in humans produces?",
      options:["酒精+CO₂","乳酸","水+CO₂","氧气"], answer:1,
      explanation:"人体无氧呼吸 Anaerobic respiration 产生乳酸 Lactic acid，导致肌肉酸痛。植物/酵母无氧呼吸产生酒精+CO₂（发酵 Fermentation）。",
      keywords:["无氧呼吸 Anaerobic respiration","乳酸 Lactic acid","发酵 Fermentation","氧气 Oxygen"], isHot:true },
];
