const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROME_PATH || undefined,headless:true});try{const p=await b.newPage({hasTouch:true});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.route('https://igcse.test/**',r=>{const f=path.join(process.cwd(),new URL(r.request().url()).pathname==='/'?'index.html':new URL(r.request().url()).pathname);return r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html'});});await p.goto(process.argv[2]==='live'?'https://nibabajiushiwo.github.io/igcse-study-platform/?release=context1':'https://igcse.test/');const result=await p.evaluate(()=>{
const roots=['question-text','options-list','q-keywords','card-front','typing-prompt','typing-hint-text','command-question','command-options'];const checks=roots.map(id=>{const el=document.getElementById(id);el.textContent='database 数据库';enhanceKeywords(el);return el.querySelectorAll('.kw-term').length===0;});
const el=document.createElement('div');el.innerHTML='<p>adatabase database database</p><p>primary key</p><a>database</a><code>database</code><pre>database</pre>';document.body.append(el);enhanceKeywords(el);const terms=[...el.querySelectorAll('.kw-term')].map(e=>e.textContent);enhanceKeywords(el);const repeat=el.querySelectorAll('.kw-term').length;kwShow(el.querySelector('.kw-term'));const tip=!document.getElementById('kw-tooltip').classList.contains('hidden');kwHide();const hide=document.getElementById('kw-tooltip').classList.contains('hidden');
const exp=document.getElementById('result-explanation');exp.textContent='database 数据库';enhanceKeywords(exp);
const ambiguous=(word,subject)=>{const box=document.createElement('div');if(subject)box.dataset.subject=subject;box.textContent=word;document.body.append(box);enhanceKeywords(box);kwShow(box.querySelector('.kw-term'));const text=document.getElementById('kw-tooltip').textContent;box.remove();return text;};
return {checks,terms,repeat,tip,hide,explanation:exp.querySelectorAll('.kw-term').length,vectorGeneric:ambiguous('vector',''),vectorPhysics:ambiguous('vector','Physics'),registerGeneric:ambiguous('register',''),registerICT:ambiguous('register','ICT')};});assert(result.checks.every(Boolean));assert.deepEqual(result.terms,['database','primary key']);assert.equal(result.repeat,2);assert(result.tip&&result.hide&&result.explanation>0);assert(result.vectorGeneric.includes('数学')&&result.vectorGeneric.includes('物理')&&result.vectorGeneric.includes('ICT'));assert(result.vectorPhysics.includes('物理')&&!result.vectorPhysics.includes('ICT'));assert(result.registerGeneric.includes('英语')&&result.registerGeneric.includes('ICT'));assert(result.registerICT.includes('ICT')&&!result.registerICT.includes('英语'));await p.evaluate(()=>{const box=document.createElement('div');box.id='kw-interaction-test';box.style.cssText='position:fixed;top:120px;left:20px;z-index:10001;background:white;padding:10px';box.textContent='database';document.body.append(box);enhanceKeywords(box);});
const term=p.locator('#kw-interaction-test .kw-term'),tip=p.locator('#kw-tooltip');
await term.focus();assert(await tip.isVisible());assert.equal(await term.getAttribute('aria-describedby'),'kw-tooltip');
await p.keyboard.press('Escape');assert(!(await tip.isVisible()));assert.equal(await term.getAttribute('aria-describedby'),null);
await p.keyboard.press('Enter');assert(await tip.isVisible());await p.keyboard.press('Space');assert(!(await tip.isVisible()));
await term.click();assert(await tip.isVisible());await term.click();assert(!(await tip.isVisible()));
await term.tap();assert(await tip.isVisible());await term.tap();assert(!(await tip.isVisible()));
await term.click();await p.evaluate(()=>refreshKeywords(document.getElementById('result-explanation')));assert(!(await tip.isVisible()));
await p.evaluate(()=>document.getElementById('kw-interaction-test').remove());
for(const width of [375,390,430,768]){await p.setViewportSize({width,height:850});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}assert.deepEqual(errors,[]);console.log('Protected test regions, context-aware subject meanings, whole words, longest phrase, skipped links/code, repeat scan and mobile widths: passed');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
