const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const fs=require('fs'),path=require('path'),assert=require('assert/strict');let b;
(async()=>{b=await chromium.launch({executablePath:process.env.CHROME_PATH,headless:true});const p=await b.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept('Updated name'));await p.route('https://igcse.test/**',r=>{const u=new URL(r.request().url()),f=path.join(process.cwd(),u.pathname==='/'?'index.html':u.pathname);r.fulfill({body:fs.readFileSync(f),contentType:f.endsWith('.js')?'application/javascript':f.endsWith('.css')?'text/css':'text/html'})});await p.goto('https://igcse.test/');await p.evaluate(()=>{currentUser={name:'QA',email:'qa@example.test',role:'owner'};appData.currentUser=currentUser;enterApp();navigateTo('materials')});
await p.locator('#upload-modal').evaluate(e=>e.classList.remove('hidden'));await p.locator('#file-input').setInputFiles({name:'biology notes.txt',mimeType:'text/plain',buffer:Buffer.from('cell membrane')});await p.locator('#upload-name').fill('Biology notes');await p.locator('#upload-subject').selectOption('生物');await p.locator('#upload-tags').fill('cells, membrane');await p.evaluate(()=>confirmUpload());await p.waitForFunction(()=>appData.materials.some(m=>m.name==='Biology notes'&&m.localFileStored));let id=await p.evaluate(()=>appData.materials.find(m=>m.name==='Biology notes').id);
assert.equal(await p.locator('.material-card').filter({hasText:'Biology notes'}).count(),1);await p.locator('#material-search').fill('membrane');assert.equal(await p.locator('.material-card').filter({hasText:'Biology notes'}).count(),1);await p.locator('#material-search').fill('missing');assert.equal(await p.locator('#materials-grid .material-card').count(),0);await p.locator('#material-search').fill('');await p.locator('#material-tag-filter').selectOption('cells');assert.equal(await p.locator('.material-card').filter({hasText:'Biology notes'}).count(),1);await p.locator('#material-tag-filter').selectOption('all');
await p.locator('.material-card').filter({hasText:'Biology notes'}).locator('button', {hasText:'改名'}).click();assert.equal(await p.evaluate(id=>appData.materials.find(m=>m.id===id).name,id),'Updated name');await p.locator('.material-card').filter({hasText:'Updated name'}).locator('button', {hasText:'编辑标签'}).click();
const backup=await p.evaluate(()=>buildBackupPayload());assert.equal(backup.materials.find(m=>m.id===id).localFileStored,undefined);assert.equal(JSON.stringify(backup).includes('cell membrane'),false);
const file=await p.evaluate(async id=>{const db=await openMaterialDB();const row=await new Promise((resolve,reject)=>{const q=db.transaction('files').objectStore('files').get(id);q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)});db.close();return row.file.text()},id);assert.equal(file,'cell membrane');
await p.evaluate(()=>navigateTo('pastpapers'));const rendered=await p.locator('#pastpapers-list').innerText();assert.match(rendered,/第三方目录/);assert.match(rendered,/官方历年真题/);assert.doesNotMatch(rendered,/核对日期 2026-09-30/);assert.equal(await p.locator('#pastpapers-list').getByText('Cambridge 官方目录入口').count(),8);assert.equal(await p.locator('#syllabus-links a').count(),9);await p.locator('#pp-subject').selectOption('物理');await p.locator('#pp-year').selectOption('2023');await p.locator('#pp-season').selectOption('m');assert.equal(await p.locator('#pastpapers-list .pastpaper-item').count(),1);assert.match(await p.locator('#pastpapers-list').innerText(),/0625/);assert.equal(await p.locator('#pastpapers-list a[href="https://www.cambridgeinternational.org/programmes-and-qualifications/cambridge-igcse-physics-0625/past-papers/"]').count(),2);await p.locator('#pp-subject').selectOption('all');await p.locator('#pp-year').selectOption('all');await p.locator('#pp-season').selectOption('sp');assert.match(await p.locator('#pastpapers-list').innerText(),/官方样卷/);
await p.evaluate(id=>deleteMaterial(id),id);assert.equal(await p.evaluate(id=>appData.materials.some(m=>m.id===id),id),false);const deleted=await p.evaluate(async id=>{const db=await openMaterialDB();const x=await new Promise(resolve=>{const q=db.transaction('files').objectStore('files').get(id);q.onsuccess=()=>resolve(q.result)});db.close();return !!x},id);assert.equal(deleted,false);assert.deepEqual(errors,[]);for(const width of [375,390,430,768]){await p.setViewportSize({width,height:900});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false)}console.log('Local attachment persistence, search/tag filter, rename/delete, backup-safe metadata, source classification, season filter and mobile widths passed');await b.close()})().catch(async e=>{console.error(e);if(b)await b.close();process.exitCode=1});
